### PR TITLE
Ammp 1209 soventix integration

### PR DESCRIPTION
**Pull request by judruizc**
Hey @svet-b, I added the `order='lsr'` parameter. I added the same driver to the config on site and have been reading much more sensible numbers now 🙂

Please let me know if there is some formatting or overall improvements I should still do.

### CODE REVIEW

**Comment by svet-b** [comment]
Thanks @judruizc ! Just to check, are the `int32` values looking reasonable too? Have in mind that the least-significant-register order will get applied to those also (since it's in `common`), thereby switching the two registers of any integer values that are stored across two registers, as well as the floats

**Comment by judruizc** [comment]
The PR had indeed not the same driver I was testing; it was an older version. I updated it and made some fixes. Also made sure I'm testing the same config that is here. 

Maybe let's give it 1 day to see if everything is good.

**Comment by svet-b** [comment]
Ok cool. So I'll hold off on merging until tomorrow?

**Comment by judruizc** [comment]
Hey @svet-b , I think you could probably merge this; as we are reading their registers correctly (now is a question on the network stability). But from the _readings_ point of view (using Modbus), I think we are complete here.

Maybe we can merge it into `dev` first ?

**Pull request merged**
